#!/bin/bash

usr="/usr/share/f123box"
etc="/etc/f123box"
#IFS=$'\n'
temp="/tmp"
#stamp=$(cat $etc/version)
source $etc/f123box.conf
#source $usr/language/$language
today=$(date +%Y%m%d)


if [ $today = $(cat $usr/last-update) ] 
then
    exit 0 #Sistema já atualizado
fi

ping -q -c 3 $repo
if [[ $? != 0 ]]  
then
    exit 1 #Servidor em manutenção
fi

urlbase="$repo/$urlpath/$language/"
mkdir -p $boxdir
cd $boxdir
wget $urlbase/md5.txt -O md5.txt

#md5sum --quiet -c md5.txt | grep \:\ FAILED | cut -f -1 -d \: | cut -f 2- -d \/ 
md5sum --quiet -c md5.txt | cut -f -1 -d \: > temp.txt

updates=$(sort temp.txt | uniq | sort - $usr/removed $usr/removed | uniq -u | cut -f 2- -d \/ )

if [ -z $updates ]
then
	echo "No updates"
	echo $today > $usr/last-update
	rm md5.txt
	rm temp.txt
	exit 0
fi

for i in $updates
do
	mkdir -p $(dirname $i)
	wget $urlbase/$i -O ./$i
done

rm temp.txt
rm md5.txt
echo $today > $usr/last-update
exit 0
